### PR TITLE
Add support for Bitbucket Server

### PR DESCRIPTION
**Pull request by knowacki23**
Hey! :)
I've noticed that there is no support for Bitbucket Server yet so I allowed myself to open a PR for that.
I wasn't sure on how to approach it when it comes to the entity annotation so I decided to go with `bitbucket-server/repo-url` annotation.

Why?

When it comes to the Bitbucket Server integration with Backstage there is a possibility to define few Bitbucket instances so it is harder to get the correct Bitbucket URL for a repository when using `project-slug`.
Also Bitbucket Server comes with custom URLs, so they will differ for each company.
More about it: https://backstage.io/docs/integrations/bitbucketServer/locations

So I thought that it would be easier and safer to add an Entity annotation which would require full URL to the Bitbucket Server repository which then is passed to `gitpodUrl`.

### CODE REVIEW

**Comment by loujaybee** [comment]
Thanks for the contribution @knowacki23 ! 

I've asked @filiptronicek to take a look at this and get it merged if possible, looks quite straight-forward to me.

**Comment by Siddhant-K-code** [comment]
For us to be able to merge this PR, can you please sign our CLA via [this DocuSign form](https://eu.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=30e1aa46-cce5-4bc6-a933-ad02cd8d5ada&env=eu&acct=86335c2c-01b9-4edc-a187-014f5150a112&v=2)

**Comment by knowacki23** [comment]
Hey @Siddhant-K-code! :)
I would need an additional signer for the CLA. How can I add that person?

**Comment by Siddhant-K-code** [comment]
> I would need an additional signer for the CLA

I think, you just need to fill up your details (rest details should be already be filled in):


image

And, in Step 2, just fill up your details, then @meysholdt will complete the further process.

**Comment by meysholdt** [comment]
hi @knowacki23 ! yes, I will be the one counter-signing from the Gitpod side. Feel free to reach me directly via moritz@gitpod.io to resolve anything related to this process.

**Comment by knowacki23** [comment]
Hey :)
I've sent you an email @meysholdt - posting about it here cause not sure if it's not gonna be blocked via some email filters :sweat_smile:

**Review by filiptronicek — APPROVED** [review]
Hey there @knowacki23, changes LGTM, thank you!

**Comment by filiptronicek** [comment]
For posterity’s sake: I have backpedaled on this and changed the `bitbucket-server/repo-url` annotation to a generic `repo-url` annotation (https://github.com/gitpod-samples/gitpod-backstage-plugin/commit/310a45459f052053e19990e1ea98bf937b977938). The reasoning is written in the commit message.

Should work as expected, either way it'd be a full context URL

**Comment by knowacki23** [comment]
Hey @filiptronicek,
Thank you for looking into it! :smiley:

**Pull request merged**
